version: '3.8'

services:
  web:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
    command: python /code/manage.py runserver ${SERVER_HOST}:${SERVER_PORT}

  db:
    image: postgres:16
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    command: ["postgres", "-c", "max_connections=300"]
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  postgres_data:
    driver: local
